name: DEVELOPER ASSISTANT
on:
  pull_request:
    types:
      - opened
  issue_comment:
 
jobs:
  pr_agent_job:
   
    runs-on: [self-hosted, genai_copilot-code-review]
    steps:
      - name: Check if commenter is a collaborator or owner/admin
        id: check_collaborator_or_owner_admin
        run: |
          if [ "${{ github.event.comment.author_association }}" == "COLLABORATOR" ] || [ "${{ github.event.comment.author_association }}" == "OWNER" ] || [ "${{ github.event.comment.author_association }}" == "MEMBER" ]; then
            echo "::set-output name=is_collaborator_or_owner_admin::true"
          else
            echo "::set-output name=is_collaborator_or_owner_admin::false"
          fi
 
      - name: PR Agent action step
        if: ((contains(github.event.comment.body, '/review') || contains(github.event.comment.body, '/describe')) && github.event.comment.user.login != 'nex-maximus' && steps.check_collaborator_or_owner_admin.outputs.is_collaborator_or_owner_admin == 'true') || github.event_name == 'pull_request' && github.event.pull_request.user.login != 'nex-maximus' && steps.check_collaborator_or_owner_admin.outputs.is_collaborator_or_owner_admin == 'true'
        id: pragent
        run: |
         cd  ../../../genai_pr_agent
         chmod +x ./get_pr_agent_details.sh
         ./get_pr_agent_details.sh
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_ACTION.AUTO_REVIEW: false
          GITHUB_ACTION.AUTO_DESCRIBE: false
          GITHUB_ACTION.UPDATE_TITLE: false
