name: CODE REVIEW REPORT
on:
  pull_request:
      types: [opened, edited, reopened, synchronize]
  issue_comment:
jobs:
  pr_agent_report:
    if: (contains(github.event.comment.body, '/generate_report') && github.event.comment.user.login != 'nex-maximus') ||
        github.event_name == 'pull_request' && github.event.pull_request.user.login != 'nex-maximus'
    runs-on: [self-hosted, genai_copilot-code-review-IAPM]
    steps:
      - name: PR Agent action step
        id: pragent
        uses: intel-innersource/frameworks.actions.maximus.genai-gpt/create-code-review-report@feature/dependent_code_review
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_ACTION.AUTO_REVIEW: false
          GITHUB_ACTION.AUTO_DESCRIBE: false
          GITHUB_ACTION.UPDATE_TITLE: false
          # Uncomment the line below to add any extra instructions you wish to give to the LLM
          # GITHUB_ACTION.EXTRA_INSTRUCTIONS: 'Please give clear review for the user'
          # Uncomment the line below to push all the suggestions for all the files as a batch instead of pushing it per file in the PR
          # GITHUB_ACTION.BATCH_SUGGESTION_PUSH: true
          # To enable dependent context from external repo/internal repo uncomment the line below and add details in .github/dependent_files.json   
          # GITHUB_ACTION.ENABLE_DEPENDENT_CONTEXT: true
